
# spring.datasource.url=jdbc:mysql://localhost:3306/jaamcareer
# spring.datasource.username=root
# spring.datasource.password='root'
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update

spring:
    application:
        name : loginservices
    dataSource:
        url: jdbc:mysql://career.cv2r0qqidi2a.us-east-1.rds.amazonaws.com:3306/career
        username: admin
        password: 'careermodel'
    jpa:
        properties:
            hibernate:
                dialect:${dataSource.dialect}
            connection:
                characterEncoding :  UTF-8
                Charset: UTF-8
                useUnicode: true
        show-sql: true
        hibernate:
            ddl-auto: none

server:
    port:
        8090
